#!/bin/bash

source "$(dirname "$(readlink -f "$0")")/environment"

{
main() {
	if ! is_vessel_mounted; then
		set_logging_enabled false
		error "vessel is not mounted"
		return 1
	fi
	"$QUANTA_CORE_SCRIPT/qv-sync" true || return $?

	msg "closing"
	"$QUANTA_CORE_SCRIPT/qv-unmount" || return $?
	return 0
}

_quanta_run_script main "$@"
exit $?
}
