#!/bin/bash

source "$(dirname "$(readlink -f "$0")")/environment"

{
main() {
	"$QUANTA_CORE_SCRIPT/qv-sync" true || return $?

	msg "closing"
	"$QUANTA_CORE_SCRIPT/qv-unmount" || return $?
	return 0
}

_quanta_run_script _quanta_mount_guard main "$@"
exit $?
}
