#!/bin/bash

source "$(dirname "$(readlink -f "$0")")/environment"

{
main() {
	local sub=
	if [ "$1" == "1" ]; then
		sub="data/chrono"
	elif [ ! -z "$1" ]; then
		sub="$1"
	fi

	#diff \
	#	-U 3 -r \
	#	--minimal \
	#	--speed-large-files \
	#	--unidirectional-new-file \
	#	| wdiff -d -n - \
	#	| colordiff \
	#	| less -R #\
	#	| vim -R -

	git diff \
		-U3 \
		--color-words \
		--minimal \
		"$QUANTA_LOCAL/$sub" \
		"$QUANTA_VESSEL/$sub"

	return 0
}

_quanta_run_script main "$@"
exit $?
}
