#!/bin/bash

source "$(dirname "$(readlink -f "$0")")/environment"

{
L_FILENAME="qm_quick.q"
L_PATH_REMOTE="/sdcard/struct/quanta/$L_FILENAME"
L_PATH_LOCAL="$QUANTA_VESSEL_DATA/mobile/$L_FILENAME"
L_PATH_SYNC="${L_PATH_LOCAL%.*}-sync.q"
L_PATH_HASH="${L_PATH_LOCAL%.*}.hash"
L_KEEP_COUNT=10

main() {
	local force="$1"

	msg "syncing mobile (quick)"
	adb shell am broadcast \
		-p "com.komiga.quanta" \
		-a "com.komiga.quanta.bridge.EXPORT_QUICK" \
		--ez "clear" true \
	> /dev/null
	if [ $? != 0 ]; then
		error "broadcast failed"
		return 2
	fi

	adb pull \
		"$L_PATH_REMOTE" \
		"$L_PATH_SYNC" \
	> /dev/null
	if [ $? != 0 ]; then
		error "pull failed"
		return 3
	fi

	if [ -f "$L_PATH_HASH" ]; then
		sha256sum --quiet --check "$L_PATH_HASH" &> /dev/null
		if [ $? == 0 ]; then
			if [ -z "$force" ]; then
				msg "already synced"
				rm "$L_PATH_SYNC"
				return 4
			else
				msg "already synced, but going ahead as instructed"
			fi
		fi
	fi
	sha256sum "$L_PATH_SYNC" > "$L_PATH_HASH"

	local keep_stub="${L_PATH_LOCAL%.*}"
	if [ -f "$keep_stub-$L_KEEP_COUNT.q" ]; then
		rm "$keep_stub-$L_KEEP_COUNT.q"
	fi
	for ((i=L_KEEP_COUNT-1; i>=1; i--)); do
		if [ -f "$keep_stub-$i.q" ]; then
			mv "$keep_stub-$i.q" "$keep_stub-$((i+1)).q"
		fi
	done

	if (( L_KEEP_COUNT > 0 )); then
		mv "$L_PATH_LOCAL" "$keep_stub-1.q"
	else
		rm "$L_PATH_LOCAL"
	fi
	mv "$L_PATH_SYNC" "$L_PATH_LOCAL"

	adb shell am broadcast \
		-p "com.komiga.quanta" \
		-a "com.komiga.quanta.bridge.REMOTE_DISCONNECT" \
	> /dev/null
	if [ $? != 0 ]; then
		warning "failed to disconnect remote"
	fi

	sbt2 "$L_PATH_LOCAL:3" &> /dev/null
	return $?
}

_quanta_run_script _quanta_mount_guard main "$@"
exit $?
}
